import { USERS } from "@/lib/mock-users";
import type { Prediction, PredictionOption, SubPrediction } from "@/lib/mock-data";
import imgCampeao from "@/assets/dd-campeao.jpg";
import imgFinal from "@/assets/dd-final.jpg";
import imgGols from "@/assets/dd-gols.jpg";
import imgBrasil from "@/assets/dd-brasil.jpg";
import imgTriplo from "@/assets/dd-triplo.jpg";
import imgOitavas from "@/assets/dd-oitavas.jpg";
import imgQuartas from "@/assets/dd-quartas.jpg";
import imgSemi from "@/assets/dd-semi.jpg";
import imgTerceiro from "@/assets/dd-terceiro.jpg";

const IMG: Record<string, string> = {
  dd1: imgCampeao, dd2: imgFinal, dd3: imgGols, dd4: imgBrasil, dd5: imgTriplo,
  dd6: imgOitavas, dd7: imgQuartas, dd8: imgSemi, dd9: imgTerceiro,
};

const REQUIREMENTS = [
  "🎯 Ter feito todas as missões",
  "🎯 Convidar 5 amigos",
];

function makeOptions(seed: number, labels: string[]): PredictionOption[] {
  return labels.map((label, i) => ({
    id: `o${i}`,
    label,
    pool: ((seed * 37 + i * 113) % 120000) + 5000,
  }));
}

const DIAMANTES: Prediction[] = [
  {
    id: "dd1",
    title: "🏆 CAMPEÃO DA COPA",
    description: `Quem levantará a taça?\n\nRequisitos:\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 📱 iPhone 17 Pro Max\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 500 Tokens`,
    category: "Desafios Diamante",
    author: USERS[0],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 500,
    entryFee: 500,
    options: makeOptions(1, ["Brasil", "Argentina", "França", "Espanha", "Alemanha", "Inglaterra", "Portugal", "Holanda", "Bélgica", "Outra Seleção"]),
    bettors: 3420,
    comments: 180,
    likes: 2100,
    shares: 450,
    tags: ["diamante", "copa", "campeão"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 50000 }],
  },
  {
    id: "dd2",
    title: "⚽ FINAL DA COPA",
    description: `Qual será o placar da grande final?\n\n🎯 Acertar o 1º, 2º e 3º colocado\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 🎮 PlayStation 5 + 💰 75.000 Tokens\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 500 Tokens`,
    category: "Desafios Diamante",
    author: USERS[1],
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 500,
    entryFee: 500,
    options: makeOptions(2, ["0x0", "1x0", "2x0", "2x1", "3x0", "3x1", "3x2", "4x0", "4x1", "4x2", "4x3", "Outro Resultado"]),
    bettors: 2890,
    comments: 210,
    likes: 1850,
    shares: 380,
    tags: ["diamante", "copa", "final"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 75000 }],
  },
  {
    id: "dd3",
    title: "⚽ QUANTOS GOLS TERÁ A COPA?",
    description: `Acertar a faixa de gols da Copa inteira\n\n🎯 Acertar o 1º, 2º e 3º colocado\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: ⚽ Bola Oficial Adidas FIFA + 💰 75.000 Tokens\n📅 Data limite para apostas: 10/07/2026\n💰 Valor para palpitar: 200 Tokens`,
    category: "Desafios Diamante",
    author: USERS[2],
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    closesAt: "2026-07-10T20:00:00.000Z",
    minTokens: 200,
    entryFee: 200,
    options: makeOptions(3, ["Até 200 gols", "201 a 220 gols", "221 a 240 gols", "241 a 260 gols", "261 a 280 gols", "281 a 300 gols", "Mais de 300 gols"]),
    bettors: 2150,
    comments: 95,
    likes: 1400,
    shares: 290,
    tags: ["diamante", "copa", "gols"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 75000 }],
  },
  {
    id: "dd4",
    title: "🇧🇷 CAMINHO DO BRASIL",
    description: `Até onde o Brasil chegará?\n\nRequisitos:\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 👕 Camiseta Oficial do Brasil + 💰 30.000 Tokens\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 200 Tokens`,
    category: "Desafios Diamante",
    author: USERS[3],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 200,
    entryFee: 200,
    options: makeOptions(4, ["Não passa da Fase de Grupos", "16 Avos de Final", "Oitavas de Final", "Quartas de Final", "Semifinal", "Vice-Campeão", "Campeão"]),
    bettors: 1980,
    comments: 145,
    likes: 1200,
    shares: 310,
    tags: ["diamante", "copa", "brasil"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 30000 }],
  },
  {
    id: "dd5",
    title: "🏆 DESAFIO DIAMANTE — TRIPLO COROA",
    description: `Acertar o Campeão + Artilheiro + Melhor Jogador\n\nRequisitos:\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 💻 Notebook Gamer + 💰 150.000 Tokens\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 500 Tokens`,
    category: "Desafios Diamante",
    author: USERS[4],
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 500,
    entryFee: 500,
    options: [],
    bettors: 4200,
    comments: 320,
    likes: 2800,
    shares: 620,
    tags: ["diamante", "copa", "triplo"],
    hot: true,
    prizeTiers: [{ hits: 3, tokens: 150000 }],
    subPredictions: [
      { id: "s1", question: "Campeão", options: ["Brasil", "Argentina", "França", "Espanha", "Alemanha", "Inglaterra", "Portugal", "Holanda"] },
      { id: "s2", question: "Artilheiro", options: ["Mbappé", "Vinícius Júnior", "Haaland", "Bellingham", "Rodrygo", "Harry Kane", "Julián Álvarez", "Outro"] },
      { id: "s3", question: "Melhor Jogador", options: ["Mbappé", "Vinícius Júnior", "Bellingham", "Rodrygo", "Pedri", "Yamal", "Haaland", "Outro"] },
    ] as SubPrediction[],
  },
  {
    id: "dd6",
    title: "🏆 DESAFIO DIAMANTE — OITAVAS DE FINAL",
    description: `⚽ Oitavas de Final\nQuantas seleções favoritas serão eliminadas?\n\nRequisitos:\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 💳 Vale-Compras R$ 1.000\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 500 Tokens`,
    category: "Desafios Diamante",
    author: USERS[5],
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 500,
    entryFee: 500,
    options: makeOptions(6, ["Nenhuma", "1 Seleção", "2 Seleções", "3 Seleções", "4 ou mais Seleções"]),
    bettors: 1560,
    comments: 78,
    likes: 980,
    shares: 210,
    tags: ["diamante", "copa", "oitavas"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 25000 }],
  },
  {
    id: "dd7",
    title: "🏆 DESAFIO DIAMANTE — QUARTAS DE FINAL",
    description: `⚽ Quartas de Final\nQuantas partidas serão decididas nos pênaltis?\n\nRequisitos:\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 💳 Vale-Compras R$ 2.000\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 500 Tokens`,
    category: "Desafios Diamante",
    author: USERS[6],
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 500,
    entryFee: 500,
    options: makeOptions(7, ["Nenhuma", "1 Partida", "2 Partidas", "3 Partidas", "Todas"]),
    bettors: 1340,
    comments: 62,
    likes: 850,
    shares: 180,
    tags: ["diamante", "copa", "quartas"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 35000 }],
  },
  {
    id: "dd8",
    title: "🏆 DESAFIO DIAMANTE — SEMIFINAL",
    description: `⚽ Semifinal\nQual será a seleção com mais gols nas semifinais?\n\nRequisitos:\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 💳 Vale-Compras R$ 5.000\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 500 Tokens`,
    category: "Desafios Diamante",
    author: USERS[7],
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 500,
    entryFee: 500,
    options: makeOptions(8, ["Brasil", "Argentina", "França", "Espanha", "Alemanha", "Inglaterra", "Portugal", "Outra"]),
    bettors: 1670,
    comments: 88,
    likes: 1100,
    shares: 240,
    tags: ["diamante", "copa", "semifinal"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 50000 }],
  },
  {
    id: "dd9",
    title: "🏆 DESAFIO DIAMANTE — DISPUTA DO 3º LUGAR",
    description: `⚽ Disputa do 3º Lugar\nQual será o placar da disputa do terceiro lugar?\n\nRequisitos:\n${REQUIREMENTS.join("\n")}\n\n🎁 Premiação: 💳 Vale-Compras R$ 3.000\n📅 Data limite para apostas: 01/07/2026\n💰 Valor para palpitar: 500 Tokens`,
    category: "Desafios Diamante",
    author: USERS[8],
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    closesAt: "2026-07-01T20:00:00.000Z",
    minTokens: 500,
    entryFee: 500,
    options: makeOptions(9, ["1x0", "2x0", "2x1", "3x0", "3x1", "3x2", "4x1", "4x2", "Empate e decisão nos pênaltis", "Outro Resultado"]),
    bettors: 1420,
    comments: 70,
    likes: 920,
    shares: 195,
    tags: ["diamante", "copa", "terceiro-lugar"],
    hot: true,
    prizeTiers: [{ hits: 1, tokens: 40000 }],
  },
];

export const DESAFIOS_DIAMANTE = DIAMANTES.map((d) => ({ ...d, imageUrl: IMG[d.id] }));
