/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Top100RouteImport } from './routes/top100'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PrevisaoIdRouteImport } from './routes/previsao.$id'
import { Route as AdminCadastrosRouteImport } from './routes/admin.cadastros'

const Top100Route = Top100RouteImport.update({
  id: '/top100',
  path: '/top100',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PrevisaoIdRoute = PrevisaoIdRouteImport.update({
  id: '/previsao/$id',
  path: '/previsao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastrosRoute = AdminCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRoute
  '/desafios': typeof DesafiosRoute
  '/empresas': typeof EmpresasRoute
  '/faq': typeof FaqRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/shop': typeof ShopRoute
  '/top100': typeof Top100Route
  '/admin/cadastros': typeof AdminCadastrosRoute
  '/previsao/$id': typeof PrevisaoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRoute
  '/desafios': typeof DesafiosRoute
  '/empresas': typeof EmpresasRoute
  '/faq': typeof FaqRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/shop': typeof ShopRoute
  '/top100': typeof Top100Route
  '/admin/cadastros': typeof AdminCadastrosRoute
  '/previsao/$id': typeof PrevisaoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRoute
  '/desafios': typeof DesafiosRoute
  '/empresas': typeof EmpresasRoute
  '/faq': typeof FaqRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/shop': typeof ShopRoute
  '/top100': typeof Top100Route
  '/admin/cadastros': typeof AdminCadastrosRoute
  '/previsao/$id': typeof PrevisaoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/criar'
    | '/desafios'
    | '/empresas'
    | '/faq'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/shop'
    | '/top100'
    | '/admin/cadastros'
    | '/previsao/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/criar'
    | '/desafios'
    | '/empresas'
    | '/faq'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/shop'
    | '/top100'
    | '/admin/cadastros'
    | '/previsao/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/criar'
    | '/desafios'
    | '/empresas'
    | '/faq'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/shop'
    | '/top100'
    | '/admin/cadastros'
    | '/previsao/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CriarRoute: typeof CriarRoute
  DesafiosRoute: typeof DesafiosRoute
  EmpresasRoute: typeof EmpresasRoute
  FaqRoute: typeof FaqRoute
  MissoesRoute: typeof MissoesRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  ShopRoute: typeof ShopRoute
  Top100Route: typeof Top100Route
  PrevisaoIdRoute: typeof PrevisaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top100': {
      id: '/top100'
      path: '/top100'
      fullPath: '/top100'
      preLoaderRoute: typeof Top100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/previsao/$id': {
      id: '/previsao/$id'
      path: '/previsao/$id'
      fullPath: '/previsao/$id'
      preLoaderRoute: typeof PrevisaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cadastros': {
      id: '/admin/cadastros'
      path: '/cadastros'
      fullPath: '/admin/cadastros'
      preLoaderRoute: typeof AdminCadastrosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCadastrosRoute: typeof AdminCadastrosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCadastrosRoute: AdminCadastrosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CriarRoute: CriarRoute,
  DesafiosRoute: DesafiosRoute,
  EmpresasRoute: EmpresasRoute,
  FaqRoute: FaqRoute,
  MissoesRoute: MissoesRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  ShopRoute: ShopRoute,
  Top100Route: Top100Route,
  PrevisaoIdRoute: PrevisaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
