/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrevisaoIdRouteImport } from './routes/previsao.$id'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisaoIdRoute = PrevisaoIdRouteImport.update({
  id: '/previsao/$id',
  path: '/previsao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/previsao/$id': typeof PrevisaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/previsao/$id': typeof PrevisaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/previsao/$id': typeof PrevisaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/previsao/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar' | '/missoes' | '/perfil' | '/ranking' | '/previsao/$id'
  id:
    | '__root__'
    | '/'
    | '/criar'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/previsao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  MissoesRoute: typeof MissoesRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  PrevisaoIdRoute: typeof PrevisaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsao/$id': {
      id: '/previsao/$id'
      path: '/previsao/$id'
      fullPath: '/previsao/$id'
      preLoaderRoute: typeof PrevisaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  MissoesRoute: MissoesRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  PrevisaoIdRoute: PrevisaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
